removed Build and test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,64 +1,97 @@
-name: GameCI Template 🎮
+name: Build WebGL and post 🎮
 
 on: push
+permissions:
+  contents: write
 
 env:
   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
 jobs:
-  testRunner:
-    name: Test in ${{ matrix.testMode }} ✨
+  checkLicense: 
+    name: Check Unity license and path
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        testMode:
-          - EditMode
-          - PlayMode
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
-
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
-
-      - name: Git LFS Pull
+      
+      - name: TestWorkingDirectory
         run: |
-          git lfs pull
-          git add .
-          git reset --hard
+          pwd
+          ls -la
+          cd "TuuksTomb"
+          pwd
+          ls -la
 
-      - name: Restore Library cache
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-test-project-${{ matrix.targetPlatform }}
-          restore-keys: |
-            Library-test-project-
-            Library-
+      - name: Fail - No license 
+        if: env.UNITY_LICENSE == ''
+        run: |
+          echo "No Unity license found. Please add your Unity license to the repository secrets."
+          exit 1
 
-      - name: Run tests
-        uses: game-ci/unity-test-runner@v2
-        id: testRunner
-        with:
-          testMode: ${{ matrix.testMode }}
-          checkName: ${{ matrix.testMode }} test results
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
+  # testRunner:
+  #   needs: checkLicense
+  #   name: Test in ${{ matrix.testMode }} ✨
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       projectPath:
+  #         - TuuksTomb
+  #       testMode:
+  #         - PlayMode
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: Test results (${{ matrix.testMode }})
-          path: ${{ steps.testRunner.outputs.artifactsPath }}
+  #     - name: print working directory and subdirectories
+  #       run: |
+  #         pwd
+  #         ls -la
+  #         echo ${{ matrix.projectPath }}
+          
+
+
+  #     - name: Create LFS file list
+  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+
+  #     - name: Restore LFS cache
+  #       uses: actions/cache@v2
+  #       id: lfs-cache
+  #       with:
+  #         path: .git/lfs
+  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+
+  #     - name: Git LFS Pull
+  #       run: |
+  #         git lfs pull
+  #         git add .
+  #         git reset --hard
+
+  #     - name: Restore Library cache
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: Library
+  #         key: Library-test-project-${{ matrix.targetPlatform }}
+  #         restore-keys: |
+  #           Library-test-project-
+  #           Library-
+
+  #     - name: Run tests
+  #       uses: game-ci/unity-test-runner@v3
+  #       id: testRunner
+  #       with:
+  #         projectPath: ${{ matrix.projectPath }}
+  #         testMode: ${{ matrix.testMode }}
+  #         checkName: ${{ matrix.testMode }} test results
+  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - uses: actions/upload-artifact@v2
+  #       with:
+  #         name: Test results (${{ matrix.testMode }})
+  #         path: ${{ steps.testRunner.outputs.artifactsPath }}
 
   buildWebGL:
-    needs: testRunner
     name: Build for WebGL 🖥️
     runs-on: ubuntu-latest
     strategy:
@@ -91,103 +124,107 @@ jobs:
           restore-keys: |
             Library-build-
             Library-
-
-      - uses: game-ci/unity-builder@v2
+      
+      - uses: game-ci/unity-builder@v3
         with:
           targetPlatform: WebGL
+          projectPath: TuuksTomb
 
       - uses: actions/upload-artifact@v2
         with:
           name: build-WebGL
           path: build/WebGL
 
-  buildWindows:
-    needs: testRunner
-    name: Build for Windows 🖥️
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # buildWindows:
+  #   needs: testRunner
+  #   name: Build for Windows 🖥️
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+  #     - name: Create LFS file list
+  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
 
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+  #     - name: Restore LFS cache
+  #       uses: actions/cache@v2
+  #       id: lfs-cache
+  #       with:
+  #         path: .git/lfs
+  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-      - name: Git LFS Pull
-        run: |
-          git lfs pull
-          git add .
-          git reset --hard
+  #     - name: Git LFS Pull
+  #       run: |
+  #         git lfs pull
+  #         git add .
+  #         git reset --hard
+        
+  #     - name: Restore Library cache
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: Library
+  #         key: Library-build-StandaloneWindows64
+  #         restore-keys: |
+  #           Library-build-
+  #           Library-
 
-      - name: Restore Library cache
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-build-StandaloneWindows64
-          restore-keys: |
-            Library-build-
-            Library-
+  #     - uses: game-ci/unity-builder@v3
+  #       with:
+  #         targetPlatform: StandaloneWindows64
+  #         projectPath: TuuksTomb
 
-      - uses: game-ci/unity-builder@v2
-        with:
-          targetPlatform: StandaloneWindows64
+  #     - uses: actions/upload-artifact@v2
+  #       with:
+  #         name: build-StandaloneWindows64
+  #         path: build/StandaloneWindows64
 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: build-StandaloneWindows64
-          path: build/StandaloneWindows64
+  # buildAndroid:
+  #   needs: testRunner
+  #   name: Build for Android 📱
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-  buildAndroid:
-    needs: testRunner
-    name: Build for Android 📱
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  #     - name: Create LFS file list
+  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
 
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+  #     - name: Restore LFS cache
+  #       uses: actions/cache@v2
+  #       id: lfs-cache
+  #       with:
+  #         path: .git/lfs
+  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+  #     - name: Git LFS Pull
+  #       run: |
+  #         git lfs pull
+  #         git add .
+  #         git reset --hard
 
-      - name: Git LFS Pull
-        run: |
-          git lfs pull
-          git add .
-          git reset --hard
+  #     - name: Restore Library cache
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: Library
+  #         key: Library-build-Android
+  #         restore-keys: |
+  #           Library-build-
+  #           Library-
 
-      - name: Restore Library cache
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-build-Android
-          restore-keys: |
-            Library-build-
-            Library-
+  #     - uses: game-ci/unity-builder@v3
+  #       with:
+  #         targetPlatform: Android
+  #         projectPath: TuuksTomb
+          
 
-      - uses: game-ci/unity-builder@v2
-        with:
-          targetPlatform: Android
-
-      - uses: actions/upload-artifact@v2
-        with:
-          name: build-Android
-          path: build/Android
+  #     - uses: actions/upload-artifact@v2
+  #       with:
+  #         name: build-Android
+  #         path: build/Android
 
 
   deployPages:
@@ -208,3 +245,12 @@ jobs:
         with:
           branch: gh-pages
           folder: build/WebGL
+  
+  post:
+    needs: deployPages
+    name: Print awesome URL 🛸
+    runs-on: ubuntu-latest
+    steps:
+      - name: URL
+        run:
+          echo https://mathiasschjoedt-bavngaard.github.io/ComputerSpilUnity/
